-- ============================================================
-- 0001_source_registry.sql — 公式情報源台帳 seed（自動生成・手編集禁止）
-- 生成元: data/source-registry/sources/*.json
-- 生成: scripts/generate-source-registry-seed.mjs
-- 方針: 台帳 JSON を正本とし、決定的 UUID で冪等に登録する（要件 §9.3）
-- ============================================================
BEGIN;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('55793112-e1ce-46e5-8090-5b41f57578b4', '千代田区（道路占用の許可申請）', '千代田区', 'https://www.city.chiyoda.lg.jp/koho/machizukuri/kotsu/shuyodoro/dorosenyo.html', 'primary_official', 'HTML', 'manual', 180, 'www.city.chiyoda.lg.jp', '千代田区ホームページのコンテンツは、特に記載がない限り自由に引用・リンク可。商用利用や転載は区へ確認。', 'https://www.city.chiyoda.lg.jp/koho/kuseijoho/sitepolicy.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('8ee69100-9ae5-43b6-826a-00d5e098a46d', '神奈川県警察（道路使用の手続）', '神奈川県警察本部', 'https://www.police.pref.kanagawa.jp/tetsuzuki/kotsukankei/mesf1016.html', 'primary_official', 'HTML', 'manual', 90, 'www.police.pref.kanagawa.jp', '政府標準利用規約（第2.0版）準拠・CC BY 4.0互換。出典記載を条件に複製・公衆送信・翻案等を自由に利用可（商用可）。第三者著作物は要事前照会。令和7年9月1日制定。', 'https://www.police.pref.kanagawa.jp/guidance.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('32aed493-fc07-45f6-8a3e-2401ca8be075', '警視庁（道路使用許可申請手続き）', '警視庁', 'https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html', 'primary_official', 'HTML', 'manual', 90, 'www.keishicho.metro.tokyo.lg.jp', '出典明示型（政府標準利用規約2.0準拠フォーマット）。利用時は「出典：警視庁ホームページ（URL）（利用年月日）」の記載が必要、編集・加工時はその旨明記。リンクは原則自由。', 'https://www.keishicho.metro.tokyo.lg.jp/about/kenri_link.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('66e7ca89-52a3-488a-826a-8b3771853719', '国土数値情報 港湾データ（C02）', '国土交通省 国土数値情報ダウンロードサービス', 'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-C02.html', 'primary_official', 'GML', 'manual', 365, 'nlftp.mlit.go.jp', '国土数値情報 使用許諾条件（非商用）準拠。出典記載（国土数値情報（港湾データ））を条件に利用可。商用利用の場合は許諾条件の確認が必要。', 'https://www.mlit.go.jp/kokudosiseki/copyright.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('786557c1-a4fb-4273-891f-78e6d8a61851', '国土数値情報 行政区域データ（N03）', '国土交通省 国土数値情報ダウンロードサービス', 'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N03-v3_0.html', 'primary_official', 'GML', 'manual', 365, 'nlftp.mlit.go.jp', '政府標準利用規約（第2.0版）準拠。出典記載（国土数値情報（行政区域データ））を条件に複製・公衆送信・翻案等を自由に利用可（商用可）。', 'https://www.mlit.go.jp/kokudosiseki/copyright.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('6e7f7900-fb8b-42c0-8678-6594f8366001', '国土数値情報 道路データ（N13）', '国土交通省 国土数値情報ダウンロードサービス', 'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N13-v2_0.html', 'primary_official', 'GML', 'manual', 365, 'nlftp.mlit.go.jp', '政府標準利用規約（第2.0版）準拠。出典記載（国土数値情報（道路データ））を条件に複製・公衆送信・翻案等を自由に利用可（商用可）。', 'https://www.mlit.go.jp/kokudosiseki/copyright.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('6a2bc219-fcc5-440e-810d-129cc9db322f', '国土数値情報 警察署データ（P18）', '国土交通省 国土数値情報ダウンロードサービス', 'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-P18.html', 'primary_official', 'GML', 'manual', 365, 'nlftp.mlit.go.jp', '政府標準利用規約（第2.0版）準拠。出典記載（国土数値情報（警察署データ））を条件に複製・公衆送信・翻案等を自由に利用可（商用可）。', 'https://www.mlit.go.jp/kokudosiseki/copyright.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('9f692190-06a1-4aef-853f-050a93369d64', '国土数値情報 河川データ（W05）', '国土交通省 国土数値情報ダウンロードサービス', 'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-W05.html', 'primary_official', 'GML', 'manual', 365, 'nlftp.mlit.go.jp', '国土数値情報 使用許諾条件（非商用）準拠。出典記載（国土数値情報（河川データ））を条件に利用可。商用利用の場合は許諾条件の確認が必要。', 'https://www.mlit.go.jp/kokudosiseki/copyright.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('52e35a8e-c5db-4202-83d5-6bae5b794ce2', '大阪市契約管財局（入札契約情報）', '大阪市契約管財局', 'https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html', 'primary_official', 'HTML', 'manual', 180, 'www.city.osaka.lg.jp', '大阪市HP著作権・免責。政府標準利用規約（第2.0版）準拠・CC BY 4.0互換。出典記載を条件に複製・公衆送信・翻案等を自由に利用可（商用可）。第三者権利コンテンツを除く。', 'https://www.city.osaka.lg.jp/main/site_policy/0000000124.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('2d48cb2f-3d3f-4b48-81b1-272c06350516', '大阪市建設局（河川等の利用（占用）の許可）', '大阪市建設局', 'https://www.city.osaka.lg.jp/kensetsu/page/0000002580.html', 'primary_official', 'HTML', 'manual', 180, 'www.city.osaka.lg.jp', '大阪市HP著作権・免責（政府標準利用規約2.0/CC BY互換・商用可・出典記載条件）。', 'https://www.city.osaka.lg.jp/main/site_policy/0000000124.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('9b4b961a-e7d6-42a3-8bb7-73cc1f31f68c', '大阪市建設局（道路占用許可申請）', '大阪市建設局', 'https://www.city.osaka.lg.jp/kensetsu/page/0000370606.html', 'primary_official', 'HTML', 'manual', 180, 'www.city.osaka.lg.jp', '大阪市HP著作権・免責（政府標準利用規約2.0/CC BY互換・商用可・出典記載条件）。', 'https://www.city.osaka.lg.jp/main/site_policy/0000000124.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('35ea6232-27b3-4aa2-80a6-7d83297e2975', '大阪府警察（道路交通法等に基づく各種申請及び届出様式）', '大阪府警察本部', 'https://www.police.pref.osaka.lg.jp/tetsuduki/dorokotsu/4971.html', 'primary_official', 'HTML', 'manual', 90, 'www.police.pref.osaka.lg.jp', '「このウェブサイトについて」（総務部広報課）。コンテンツの著作権は大阪府警察本部等に帰属し、私的使用・引用等を除き無断で転用・引用不可（制限型）。政府標準利用規約/CC BY非適用。', 'https://www.police.pref.osaka.lg.jp/8808.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('277bd27c-310e-48c0-843b-2dc0aa65b1ac', '大阪港湾局', '大阪港湾局（大阪市・大阪府の港湾管理を一元化した組織）', 'https://www.city.osaka.lg.jp/port/', 'primary_official', 'HTML', 'manual', 90, 'www.city.osaka.lg.jp', '大阪市HP著作権・免責（政府標準利用規約2.0/CC BY互換・商用可・出典記載条件）。', 'https://www.city.osaka.lg.jp/main/site_policy/0000000124.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('5f415257-92df-4914-89c1-6b6ac5bf3af8', '東京都建設局（河川の管理と活用）', '東京都建設局', 'https://www.kensetsu.metro.tokyo.lg.jp/river/kanri', 'primary_official', 'HTML', 'manual', 180, 'www.kensetsu.metro.tokyo.lg.jp', '東京都公式HPの著作権ポリシー（制限型）。私的使用・引用等を除き無断複製・転用は不可。', 'https://www.metro.tokyo.lg.jp/policy/chosakuken', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', '東京都建設局（道路の管理）', '東京都建設局', 'https://www.kensetsu.metro.tokyo.lg.jp/road/kanri', 'primary_official', 'HTML', 'manual', 180, 'www.kensetsu.metro.tokyo.lg.jp', '東京都公式HPの著作権ポリシー（制限型）。私的使用・引用等を除き無断複製・転用は不可。政府標準利用規約/CC BY非適用。', 'https://www.metro.tokyo.lg.jp/policy/chosakuken', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('dda736cd-0cc1-45bb-816b-0739bef2e6b0', '東京都港湾局（お問い合わせ窓口一覧）', '東京都港湾局', 'https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi', 'primary_official', 'HTML', 'manual', 90, 'www.kouwan.metro.tokyo.lg.jp', '東京都公式HPの著作権ポリシー（制限型）。私的使用・引用等を除き無断複製・転用は不可。', 'https://www.metro.tokyo.lg.jp/policy/chosakuken', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('75e86800-3359-4fae-85eb-bbdb9c08aa95', '東京都財務局（契約情報）', '東京都財務局', 'https://www.zaimu.metro.tokyo.lg.jp/keiyaku', 'primary_official', 'HTML', 'manual', 180, 'www.zaimu.metro.tokyo.lg.jp', '東京都公式HPの著作権ポリシー（制限型）。私的使用・引用等の著作権法上認められた場合を除き無断複製・転用は不可。政府標準利用規約/CC BY非適用。転載は各ページ問合せ先へ要相談。', 'https://www.metro.tokyo.lg.jp/policy/chosakuken', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('d61fd0e5-7a76-48d6-8b08-4de34276d534', '横浜市 神奈川区役所', '横浜市', 'https://www.city.yokohama.lg.jp/kanagawa/madoguchi-shisetsu/kuyakusho/', 'primary_official', 'HTML', 'manual', 180, 'www.city.yokohama.lg.jp', '横浜市ホームページの著作物は出典を明示して引用可能。商用利用は市へ確認。', 'https://www.city.yokohama.lg.jp/koho/koho-seisaku/policy/linksite.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('913fc3b1-0406-4397-8760-c1424c0d9cee', '横浜市（河川・一般下水道（水路）占用等の手続き）', '横浜市（道路局河川部/下水道河川局）', 'https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/kasen-gesuido/kasen/youchi/20200715131717128.html', 'primary_official', 'HTML', 'manual', 180, 'www.city.yokohama.lg.jp', '横浜市サイトポリシー（既定は制限型、CC BY表記ページのみ二次利用可）。', 'https://www.city.yokohama.lg.jp/aboutweb/sitepolicy.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('87ec249b-62a0-4c23-8043-e2e484fb2d9b', '横浜市港湾局（港湾局の紹介）', '横浜市港湾局', 'https://www.city.yokohama.lg.jp/city-info/yokohamashi/org/kowan/', 'primary_official', 'HTML', 'manual', 90, 'www.city.yokohama.lg.jp', '横浜市サイトポリシー（既定は制限型、CC BY表記ページのみ二次利用可）。', 'https://www.city.yokohama.lg.jp/aboutweb/sitepolicy.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('64b72adc-beb7-4ff8-83ae-73a966383a80', '横浜市（入札・契約）', '横浜市（財政局契約第一課ほか）', 'https://www.city.yokohama.lg.jp/business/nyusatsu/', 'primary_official', 'HTML', 'manual', 180, 'www.city.yokohama.lg.jp', '著作権は原則横浜市所有（既定は制限型：私的使用・引用等を除き無断複製・転用不可）。CC BY 4.0 が明記されたページ/データのみ出典表示のもと商用含む二次利用可。数値データ・簡単な表等は自由利用。', 'https://www.city.yokohama.lg.jp/aboutweb/sitepolicy.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
INSERT INTO provenance.data_sources (id, name, publisher, base_url, authority, format, fetch_mode, ttl_days, allowed_host, license_text, license_url, active)
VALUES ('c19d9c16-53e3-427a-8d80-9f99d203d58f', '横浜市（道路の占用）', '横浜市道路局', 'https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/doro/kanri_senyo/senyo/', 'primary_official', 'HTML', 'manual', 180, 'www.city.yokohama.lg.jp', '横浜市サイトポリシー。既定は制限型（私的使用・引用等を除き無断複製・転用不可）。CC BY表記ページのみ出典表示で二次利用可。', 'https://www.city.yokohama.lg.jp/aboutweb/sitepolicy.html', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, publisher = EXCLUDED.publisher, base_url = EXCLUDED.base_url, authority = EXCLUDED.authority, format = EXCLUDED.format, fetch_mode = EXCLUDED.fetch_mode, ttl_days = EXCLUDED.ttl_days, allowed_host = EXCLUDED.allowed_host, license_text = EXCLUDED.license_text, license_url = EXCLUDED.license_url, active = EXCLUDED.active;
COMMIT;
