-- ============================================================
-- 0002_staging_org_imports.sql — 組織レコードのステージング取込（自動生成・手編集禁止）
-- 生成元: data/source-registry/sources/*.json
-- 生成: scripts/generate-entity-imports.mjs
-- 方針: 無レビュー公開禁止（§6.2）。必ず pending で登録し、SCR-07 で二者レビュー後に公開する
-- ============================================================
BEGIN;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('8cd1ba76-3688-4411-86a2-17e573d0c92a', '55793112-e1ce-46e5-8090-5b41f57578b4', 'organization', '{"canonicalName":"千代田区","sourceName":"千代田区（道路占用の許可申請）","organizationType":"road_admin","officialUrl":"https://www.city.chiyoda.lg.jp/koho/machizukuri/kotsu/shuyodoro/dorosenyo.html","region":"tokyo","sourceSlug":"chiyoda-road-senyo","notes":"千代田区管理道路の占用許可窓口（環境まちづくり総務課 占用係）。市区町村（特別区）単位の窓口整備の代表例として追加。他の特別区・政令指定都市の区も同様の手順で収集する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('6b72d377-2fd1-4a28-8e25-e0c54ab01073', '8ee69100-9ae5-43b6-826a-00d5e098a46d', 'organization', '{"canonicalName":"神奈川県警察本部","sourceName":"神奈川県警察（道路使用の手続）","organizationType":"police","officialUrl":"https://www.police.pref.kanagawa.jp/tetsuzuki/kotsukankei/mesf1016.html","region":"yokohama","sourceSlug":"kanagawa-police-road-use","notes":"申請は道路使用場所を管轄する各警察署の道路使用窓口。県内2管轄以上は出発地/主使用地の警察署へ。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('2a0fd6a9-cf09-42de-8c1e-6ebb5a9d1571', '32aed493-fc07-45f6-8a3e-2401ca8be075', 'organization', '{"canonicalName":"警視庁","sourceName":"警視庁（道路使用許可申請手続き）","organizationType":"police","officialUrl":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","region":"tokyo","sourceSlug":"keishicho-road-use","notes":"申請は使用場所を管轄する警察署の交通規制係。都公式HPとは別の独自著作権ページ（出典明示型）を持つ。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('7b06d6ee-effb-483f-8058-08f77a9827ef', '66e7ca89-52a3-488a-826a-8b3771853719', 'organization', '{"canonicalName":"国土交通省 国土数値情報ダウンロードサービス","sourceName":"国土数値情報 港湾データ（C02）","organizationType":"port_admin","officialUrl":"https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-C02.html","region":"national","sourceSlug":"mlit-ksj-c02","notes":"全国の港湾データ（港湾区域境界は LineString のためポリゴン化処理が必要）。代表3地域の主要港湾（東京港・横浜港・大阪港）から着手する。CRS を EPSG:4326 へ変換してからステージング取込する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('3a449423-93b7-462a-8443-17c566bc4b07', '786557c1-a4fb-4273-891f-78e6d8a61851', 'organization', '{"canonicalName":"国土交通省 国土数値情報ダウンロードサービス","sourceName":"国土数値情報 行政区域データ（N03）","organizationType":"prefecture","officialUrl":"https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N03-v3_0.html","region":"national","sourceSlug":"mlit-ksj-n03","notes":"全国の行政区域ポリゴン（約500m精度・作成年に注意）。N03-20240101 等の版を取得し、CRS を EPSG:4326 へ変換してからステージング取込する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('91aff7ae-fd8c-4084-8131-c3ba0f1653e1', '6e7f7900-fb8b-42c0-8678-6594f8366001', 'organization', '{"canonicalName":"国土交通省 国土数値情報ダウンロードサービス","sourceName":"国土数値情報 道路データ（N13）","organizationType":"road_admin","officialUrl":"https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N13-v2_0.html","region":"national","sourceSlug":"mlit-ksj-n13","notes":"全国の道路ラインデータ。管轄ポリゴン化の際は路線単位（N13_002 等）へ集約し、CRS を EPSG:4326 へ変換してからステージング取込する。代表3地域から着手し、二者レビュー後に core 反映する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('23a202e6-135f-4180-86d8-8025fb0974de', '6a2bc219-fcc5-440e-810d-129cc9db322f', 'organization', '{"canonicalName":"国土交通省 国土数値情報ダウンロードサービス","sourceName":"国土数値情報 警察署データ（P18）","organizationType":"police","officialUrl":"https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-P18.html","region":"national","sourceSlug":"mlit-ksj-p18","notes":"警察署の位置データ（点）。管轄区域の公式ポリゴンは提供されないため、行政区域との重なりや距離で推定区域（estimated=true・precision=interpreted）として整備する。README の注意事項（警察署の管轄には推定が含まれる）を画面表示へ必ず反映する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('e5f616c7-2ab5-44e0-8d06-7681b13da646', '9f692190-06a1-4aef-853f-050a93369d64', 'organization', '{"canonicalName":"国土交通省 国土数値情報ダウンロードサービス","sourceName":"国土数値情報 河川データ（W05）","organizationType":"river_admin","officialUrl":"https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-W05.html","region":"national","sourceSlug":"mlit-ksj-w05","notes":"全国の河川ラインデータ（Stream）。河川名で集約し、代表3地域の主要河川から管轄区域として整備する。ラインデータはバッファまたは行政区域との重なりで管轄表現する。CRS を EPSG:4326 へ変換してからステージング取込する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('9b0f8eb7-1b95-4a3c-8af4-448f0ebe7ab0', '16d6ce7e-d91d-477f-8963-dd26ebf12214', 'organization', '{"canonicalName":"大阪市","sourceName":"大阪市役所","organizationType":"municipality","officialUrl":"https://www.city.osaka.lg.jp/","region":"osaka","sourceSlug":"osaka-city-hall","notes":"大阪市役所（本庁）の代表窓口。市区町村（政令指定都市）単位の窓口整備の代表例。各区役所（北区・中央区等）は同様の手順で収集する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('fefac55c-3025-401a-806c-d5ce23d4b755', '52e35a8e-c5db-4202-83d5-6bae5b794ce2', 'organization', '{"canonicalName":"大阪市契約管財局","sourceName":"大阪市契約管財局（入札契約情報）","organizationType":"issuer","officialUrl":"https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html","region":"osaka","sourceSlug":"osaka-keiyaku-nyusatsu","notes":"工事請負入札等情報は同局サイト内 category 3047-3。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('9871c04c-83ae-4b67-8b0e-eefed7e9f362', '2d48cb2f-3d3f-4b48-81b1-272c06350516', 'organization', '{"canonicalName":"大阪市建設局","sourceName":"大阪市建設局（河川等の利用（占用）の許可）","organizationType":"river_admin","officialUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000002580.html","region":"osaka","sourceSlug":"osaka-kensetsu-river","notes":"市管理河川が対象。一級河川・府管理河川等は大阪府所管となり、対象により管理者が分岐する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('66175181-9226-444b-8f1c-d4963be53e47', '9b4b961a-e7d6-42a3-8bb7-73cc1f31f68c', 'organization', '{"canonicalName":"大阪市建設局","sourceName":"大阪市建設局（道路占用許可申請）","organizationType":"road_admin","officialUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000370606.html","region":"osaka","sourceSlug":"osaka-kensetsu-road","notes":"認定道路への足場・仮囲等の設置に占用許可。建設局道路河川部道路課等。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('e9287e22-f3fb-4317-8340-25d39ab4fbdc', '35ea6232-27b3-4aa2-80a6-7d83297e2975', 'organization', '{"canonicalName":"大阪府警察本部","sourceName":"大阪府警察（道路交通法等に基づく各種申請及び届出様式）","organizationType":"police","officialUrl":"https://www.police.pref.osaka.lg.jp/tetsuduki/dorokotsu/4971.html","region":"osaka","sourceSlug":"osaka-police-shinsei","notes":"道路使用許可申請は所轄警察署へ。令和7年12月15日よりe-Gov電子申請対応の案内あり。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('08fab8e5-1e9e-4add-8d2e-182cb8fd0eb3', '277bd27c-310e-48c0-843b-2dc0aa65b1ac', 'organization', '{"canonicalName":"大阪港湾局（大阪市・大阪府の港湾管理を一元化した組織）","sourceName":"大阪港湾局","organizationType":"port_admin","officialUrl":"https://www.city.osaka.lg.jp/port/","region":"osaka","sourceSlug":"osaka-port","notes":"2020/10に大阪市港湾局と大阪府港湾局を統合。大阪港と府営港湾8港を管理。掲載実体のある city.osaka.lg.jp を正本とした。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('4b58b4af-aaa3-42a9-8a19-749eec031794', '5f415257-92df-4914-89c1-6b6ac5bf3af8', 'organization', '{"canonicalName":"東京都建設局","sourceName":"東京都建設局（河川の管理と活用）","organizationType":"river_admin","officialUrl":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","region":"tokyo","sourceSlug":"tokyo-kensetsu-river","notes":"河川敷地占用の申請様式は /river/yoshiki/kasen_shikichi。建設局河川部が所管。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('6b829cac-1baf-4199-8977-73cb77dde2bc', 'c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', 'organization', '{"canonicalName":"東京都建設局","sourceName":"東京都建設局（道路の管理）","organizationType":"road_admin","officialUrl":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","region":"tokyo","sourceSlug":"tokyo-kensetsu-road","notes":"都道の道路占用が対象。占用申請様式は /application/youshiki/douro_senyo。同局が道路と河川を所管。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('e21da357-1068-4d60-86a6-2334668c076b', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'organization', '{"canonicalName":"東京都港湾局","sourceName":"東京都港湾局（お問い合わせ窓口一覧）","organizationType":"port_admin","officialUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","region":"tokyo","sourceSlug":"tokyo-kouwan-madoguchi","notes":"占用専用ページが公式サイト内に特定できず窓口案内を代表URLとした。港湾施設の占用実務は東京港港湾情報システム等の別系統。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('08adf206-e00d-4d56-82e4-eeb8ce26e326', '75e86800-3359-4fae-85eb-bbdb9c08aa95', 'organization', '{"canonicalName":"東京都財務局","sourceName":"東京都財務局（契約情報）","organizationType":"issuer","officialUrl":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","region":"tokyo","sourceSlug":"tokyo-zaimu-keiyaku","notes":"財務局は東京都統一CMS上にあり著作権方針は都庁総合HPに集約。実手続は東京都電子調達システムへ誘導。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('901b3c10-6d20-4eed-84ba-938a388ef056', 'd61fd0e5-7a76-48d6-8b08-4de34276d534', 'organization', '{"canonicalName":"横浜市","sourceName":"横浜市 神奈川区役所","organizationType":"municipality","officialUrl":"https://www.city.yokohama.lg.jp/kanagawa/madoguchi-shisetsu/kuyakusho/","region":"yokohama","sourceSlug":"yokohama-kanagawa-ku","notes":"横浜市神奈川区役所の代表窓口。市区町村（政令指定都市の区）単位の窓口整備の代表例。他区（鶴見・中・西・港北等）も同様の手順で収集する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('5bef6069-46cf-4b17-8485-bf211b4372d8', '913fc3b1-0406-4397-8760-c1424c0d9cee', 'organization', '{"canonicalName":"横浜市（道路局河川部/下水道河川局）","sourceName":"横浜市（河川・一般下水道（水路）占用等の手続き）","organizationType":"river_admin","officialUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/kasen-gesuido/kasen/youchi/20200715131717128.html","region":"yokohama","sourceSlug":"yokohama-kasen-senyo","notes":"市管理河川の占用。一級河川等の県管理河川は神奈川県（横浜川崎治水事務所）所管のため、対象河川の等級で管理者が分岐する。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('14459a3c-93b3-4c82-8b84-6bbcfe7a1242', '87ec249b-62a0-4c23-8043-e2e484fb2d9b', 'organization', '{"canonicalName":"横浜市港湾局","sourceName":"横浜市港湾局（港湾局の紹介）","organizationType":"port_admin","officialUrl":"https://www.city.yokohama.lg.jp/city-info/yokohamashi/org/kowan/","region":"yokohama","sourceSlug":"yokohama-kowan","notes":"港湾管財課・施設管理課・水域管理課等が施設/水域を所管。占用等の個別手続は各課問合せ。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('30d55517-e337-4df0-81e7-1564df749034', '64b72adc-beb7-4ff8-83ae-73a966383a80', 'organization', '{"canonicalName":"横浜市（財政局契約第一課ほか）","sourceName":"横浜市（入札・契約）","organizationType":"issuer","officialUrl":"https://www.city.yokohama.lg.jp/business/nyusatsu/","region":"yokohama","sourceSlug":"yokohama-nyusatsu","notes":"工事の一般競争入札は別ドメイン「ヨコハマ・入札のとびら」(keiyaku.city.yokohama.lg.jp)。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('0490f8a9-3da8-49ae-8df6-4453fe0d3487', 'c19d9c16-53e3-427a-8d80-9f99d203d58f', 'organization', '{"canonicalName":"横浜市道路局","sourceName":"横浜市（道路の占用）","organizationType":"road_admin","officialUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/doro/kanri_senyo/senyo/","region":"yokohama","sourceSlug":"yokohama-road-senyo","notes":"道路占用許可基準ページあり。実際の申請窓口は各区土木事務所。"}'::jsonb, '[]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
COMMIT;
