-- ============================================================
-- 0005_staging_tokyo_office_contacts.sql — 窓口・連絡先のステージング取込（自動生成・手編集禁止）
-- 生成元: data/source-registry/entities/**/*.json
-- 生成: scripts/generate-office-contact-imports.mjs
-- 方針: 無レビュー公開禁止（§6.2）。pending + contact_pending_review で登録し、二者レビュー後に公開する
-- ============================================================
BEGIN;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('19ffc09e-e1f8-4292-8b7f-233c065fda79', '32aed493-fc07-45f6-8a3e-2401ca8be075', 'office', '{"entityKind":"office","sourceSlug":"keishicho-road-use","organizationName":"警視庁","officeName":"交通規制課 道路第一係・道路第二係","roleSummary":"道路使用許可の概要、工事・作業（道路第一係）および工事・作業以外（道路第二係）に関する問い合わせ","postalCode":"100-8929","addressRaw":"東京都千代田区霞が関2丁目1番1号（警視庁）","receptionNote":"申請窓口は使用場所を管轄する警察署の交通規制係（受付 平日8:30〜16:30）。高速道路上は高速道路交通警察隊へ申請。","sourceUrl":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","confirmedAt":"2026-08-13","notes":"申請書類・様式の詳細は原典を確認。代表番号は問い合わせ先として記載されており、直接の担当係へつながるとは限らない。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('9c756d7a-59be-4cae-830e-68a7542ce3b5', '32aed493-fc07-45f6-8a3e-2401ca8be075', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"keishicho-road-use","officeName":"交通規制課 道路第一係・道路第二係","contactType":"phone","label":"警視庁代表（交通規制課）","displayValue":"03-3581-4321","extension":null,"sourceUrl":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('d5e75534-3d97-4a96-817b-3815d710588e', '32aed493-fc07-45f6-8a3e-2401ca8be075', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"keishicho-road-use","officeName":"交通規制課 道路第一係・道路第二係","contactType":"web","label":"道路使用許可申請手続き（原典）","displayValue":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","extension":null,"sourceUrl":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a58271fd-1054-4109-8d1a-4a35ccedc7fb', '5f415257-92df-4914-89c1-6b6ac5bf3af8', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kensetsu-river","organizationName":"東京都建設局","officeName":"河川部 指導調整課 占用担当","roleSummary":"河川占用等に関する問い合わせ（原典「指導調整課占用担当」）","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","confirmedAt":"2026-08-13","notes":"河川利用全般の問い合わせは所管の建設事務所管理課または特別区へ（原典に記載・所管区域は別ページ参照）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('2b3d803f-21f7-422d-881a-322869aa1163', '5f415257-92df-4914-89c1-6b6ac5bf3af8', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-river","officeName":"河川部 指導調整課 占用担当","contactType":"phone","label":"問い合わせ（占用担当）","displayValue":"03-5320-5409","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('6136d82e-28c2-4d9e-829a-14bd34d2cb30', '5f415257-92df-4914-89c1-6b6ac5bf3af8', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-river","officeName":"河川部 指導調整課 占用担当","contactType":"web","label":"河川の管理と活用（原典）","displayValue":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('25beae98-2cf7-4575-8965-b65cdefb36a4', 'c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kensetsu-road","organizationName":"東京都建設局","officeName":"道路管理部 管理課","roleSummary":"都道の占用許可・特殊車両通行許可等に関する問い合わせ窓口（原典「問い合わせ先：管理課」）","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":"原典ページに受付時間の記載なし（要照会）","sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","confirmedAt":"2026-08-13","notes":"2026-08-13 に公式ページを取得して抽出。道路管理部の組織概要・パンフレット問い合わせ先として管理課 03-5320-5273 を確認。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('625bca7d-6c47-4304-8f46-83d13ea7f638', 'c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-road","officeName":"道路管理部 管理課","contactType":"phone","label":"問い合わせ（管理課）","displayValue":"03-5320-5273","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('e090cb03-9d5e-47d6-865a-83d687929883', 'c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-road","officeName":"道路管理部 管理課","contactType":"web","label":"道路の管理（原典）","displayValue":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('1e6daa69-de65-4de5-8eb6-51169f8a5d9d', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kouwan-madoguchi","organizationName":"東京都港湾局","officeName":"総務部総務課 広報・国際担当（都民の声総合窓口）","roleSummary":"東京都港湾局の事業に関する総合的な問い合わせ窓口","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13","notes":"提言・要望等はメールでも受付（原典「提言・要望等」ページ参照）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a833c86f-96fa-4e22-8094-dbe6e2ed40f6', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"総務部総務課 広報・国際担当（都民の声総合窓口）","contactType":"phone","label":"港湾局都民の声総合窓口","displayValue":"03-5320-5524","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('16855fec-bf57-4324-8c0d-f6774ee7225e', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"総務部総務課 広報・国際担当（都民の声総合窓口）","contactType":"web","label":"窓口一覧（原典）","displayValue":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a5d00d4c-1fb8-420a-8d5e-63054cc95bd5', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kouwan-madoguchi","organizationName":"東京都港湾局","officeName":"東京港建設事務所 高潮対策センター 防災担当","roleSummary":"水門・陸こうの工事・定期運転についての問い合わせ","postalCode":null,"addressRaw":null,"receptionNote":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13","notes":"住所・受付時間は原典の東京港建設事務所ページを確認すること。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('853941fd-8510-4aa2-8ae9-63356e51417f', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"東京港建設事務所 高潮対策センター 防災担当","contactType":"phone","label":"防災担当","displayValue":"03-3521-3013","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('c99bb39a-03ed-4ff0-8f10-65f48a538688', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"東京港建設事務所 高潮対策センター 防災担当","contactType":"web","label":"窓口一覧（原典）","displayValue":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('03a2fb3d-ed3c-4f10-8b62-334bd7d7b0eb', '75e86800-3359-4fae-85eb-bbdb9c08aa95', 'office', '{"entityKind":"office","sourceSlug":"tokyo-zaimu-keiyaku","organizationName":"東京都財務局","officeName":"経理部総務課 契約調整担当","roleSummary":"契約情報・入札契約に関する問い合わせ","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":null,"sourceUrl":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","confirmedAt":"2026-08-13","notes":"入札手続きの操作等は東京都電子調達システムの案内を確認すること。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('0b0e7730-bba7-4851-8997-141313f7541f', '75e86800-3359-4fae-85eb-bbdb9c08aa95', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-zaimu-keiyaku","officeName":"経理部総務課 契約調整担当","contactType":"phone","label":"問い合わせ（契約調整担当）","displayValue":"03-5388-2607","extension":null,"sourceUrl":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('583012cc-cb3b-454b-85b0-35bb34981a8c', '75e86800-3359-4fae-85eb-bbdb9c08aa95', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-zaimu-keiyaku","officeName":"経理部総務課 契約調整担当","contactType":"web","label":"契約情報（原典）","displayValue":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","extension":null,"sourceUrl":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
COMMIT;
