-- ============================================================
-- 0005_staging_office_contacts.sql — 窓口・連絡先のステージング取込（自動生成・手編集禁止）
-- 生成元: data/source-registry/entities/**/*.json
-- 生成: scripts/generate-office-contact-imports.mjs
-- 方針: 無レビュー公開禁止（§6.2）。pending + contact_pending_review で登録し、二者レビュー後に公開する
-- ============================================================
BEGIN;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('79281887-e7cc-4de8-85e4-66525792ba9f', '52e35a8e-c5db-4202-83d5-6bae5b794ce2', 'office', '{"entityKind":"office","sourceSlug":"osaka-keiyaku-nyusatsu","organizationName":"大阪市契約管財局","officeName":"契約管財局（入札契約情報）","roleSummary":"大阪市の工事請負入札等・契約情報の掲載主体。入札手続きの詳細は東京都電子調達と同様に案内ページを参照","postalCode":"530-8201","addressRaw":"大阪市北区中之島1丁目3番20号（大阪市役所）","receptionNote":"開庁時間 平日9:00〜17:30（土日祝・年末年始を除く）。","sourceUrl":"https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html","confirmedAt":"2026-08-13","notes":"契約担当部署の直通番号は原典に記載なし（要照会）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('3716382d-a75b-4143-8709-741a2aeefd00', '52e35a8e-c5db-4202-83d5-6bae5b794ce2', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-keiyaku-nyusatsu","officeName":"契約管財局（入札契約情報）","contactType":"phone","label":"大阪市役所代表","displayValue":"06-6208-8181","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a7f9243b-d91c-4848-899f-2c97e8cf8b21', '52e35a8e-c5db-4202-83d5-6bae5b794ce2', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-keiyaku-nyusatsu","officeName":"契約管財局（入札契約情報）","contactType":"phone","label":"大阪市総合コールセンター（8:00〜21:00）","displayValue":"06-4301-7285","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('cea847fd-9169-4dfc-84bc-28d7d0ff05ce', '52e35a8e-c5db-4202-83d5-6bae5b794ce2', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-keiyaku-nyusatsu","officeName":"契約管財局（入札契約情報）","contactType":"web","label":"大阪市契約管財局 入札契約情報（原典）","displayValue":"https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/keiyakukanzai/category/3047-0-0-0-0-0-0-0-0-0.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('e8fe866a-d974-4bf7-8e25-c06820f8149a', '2d48cb2f-3d3f-4b48-81b1-272c06350516', 'office', '{"entityKind":"office","sourceSlug":"osaka-kensetsu-river","organizationName":"大阪市建設局","officeName":"建設局 道路河川部 河川課","roleSummary":"大阪市管理河川の占用許可・利用手続きの窓口（河川等占用許可申請）","postalCode":"559-0034","addressRaw":"大阪市住之江区南港北2丁目1番10号 ATCビルITM棟6階","receptionNote":"申請書類は送付または持参（持参は平日9:00〜12:15・13:00〜17:30）。","sourceUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000002580.html","confirmedAt":"2026-08-13","notes":"一級河川・府管理河川等は大阪府等の所管となるため、対象により管理者が分岐する（原典注記）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('ba104d09-0a75-4b6d-8f6f-cd61eef84623', '2d48cb2f-3d3f-4b48-81b1-272c06350516', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-kensetsu-river","officeName":"建設局 道路河川部 河川課","contactType":"phone","label":"河川課","displayValue":"06-6615-6833","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000002580.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('fcb3649f-2457-4545-8209-634b0bdafdbd', '2d48cb2f-3d3f-4b48-81b1-272c06350516', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-kensetsu-river","officeName":"建設局 道路河川部 河川課","contactType":"web","label":"河川等の利用（占用）の許可（原典）","displayValue":"https://www.city.osaka.lg.jp/kensetsu/page/0000002580.html","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000002580.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('b2ef9fb5-5a66-41ef-86f4-1cc1d865b024', '9b4b961a-e7d6-42a3-8bb7-73cc1f31f68c', 'office', '{"entityKind":"office","sourceSlug":"osaka-kensetsu-road","organizationName":"大阪市建設局","officeName":"建設局 総務部 管理課","roleSummary":"大阪市管理道路（認定道路）の占用許可申請窓口","postalCode":"559-0034","addressRaw":"大阪市住之江区南港北2丁目1番10号 ATCビルITM棟6階","receptionNote":"申請窓口は管理課と各工営所にあり、占用物件の種類・設置場所によって異なる（原典参照）。","sourceUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000370606.html","confirmedAt":"2026-08-13","notes":"国道指定区間・高速自動車国道・府道等は各管理者（大阪国道事務所等）へ。境界付近は各工営所へ。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a8b115d2-31a7-406d-8bec-f666e9ded1cc', '9b4b961a-e7d6-42a3-8bb7-73cc1f31f68c', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-kensetsu-road","officeName":"建設局 総務部 管理課","contactType":"phone","label":"管理課","displayValue":"06-6615-6678","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000370606.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('02421eb3-7267-4628-8951-4fff5365f75d', '9b4b961a-e7d6-42a3-8bb7-73cc1f31f68c', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-kensetsu-road","officeName":"建設局 総務部 管理課","contactType":"web","label":"道路・橋梁の管理、道路占用許可申請（原典）","displayValue":"https://www.city.osaka.lg.jp/kensetsu/page/0000370606.html","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/kensetsu/page/0000370606.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('95abe1e8-a6f2-452a-8ce0-5d34018704b8', '35ea6232-27b3-4aa2-80a6-7d83297e2975', 'office', '{"entityKind":"office","sourceSlug":"osaka-police-shinsei","organizationName":"大阪府警察本部","officeName":"大阪府警察本部（交通規制課・交通総務課）","roleSummary":"道路使用許可等の申請・届出の様式掲載主体。通行可標章は交通規制課、特定自動運行等は交通総務課へ問い合わせ","postalCode":"540-8540","addressRaw":"大阪市中央区大手前三丁目1番11号（大阪府警察本部）","receptionNote":"申請は使用場所を管轄する警察署へ（警察署一覧は原典参照）。e-Gov電子申請にも対応。","sourceUrl":"https://www.police.pref.osaka.lg.jp/tetsuduki/dorokotsu/4971.html","confirmedAt":"2026-08-13","notes":"代表番号は問い合わせ先であり、担当係へ直通するとは限らない。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('8bdac739-9ae7-439d-8eb3-961971a9fa7b', '35ea6232-27b3-4aa2-80a6-7d83297e2975', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-police-shinsei","officeName":"大阪府警察本部（交通規制課・交通総務課）","contactType":"phone","label":"大阪府警察本部代表","displayValue":"06-6943-1234","extension":null,"sourceUrl":"https://www.police.pref.osaka.lg.jp/tetsuduki/dorokotsu/4971.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('69de55bf-a28d-4e8f-83b9-b683be76ff20', '35ea6232-27b3-4aa2-80a6-7d83297e2975', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-police-shinsei","officeName":"大阪府警察本部（交通規制課・交通総務課）","contactType":"web","label":"道路交通法等に基づく各種申請及び届出様式（原典）","displayValue":"https://www.police.pref.osaka.lg.jp/tetsuduki/dorokotsu/4971.html","extension":null,"sourceUrl":"https://www.police.pref.osaka.lg.jp/tetsuduki/dorokotsu/4971.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('3a597b5b-dec2-4b86-8f8f-5994825c4cc8', '277bd27c-310e-48c0-843b-2dc0aa65b1ac', 'office', '{"entityKind":"office","sourceSlug":"osaka-port","organizationName":"大阪港湾局（大阪市・大阪府の港湾管理を一元化した組織）","officeName":"大阪港湾局（組織・問合せ一覧）","roleSummary":"大阪港と府営港湾8港の管理・事業に関する問い合わせ（組織・問合せ一覧ページを参照）","postalCode":"530-8201","addressRaw":"大阪市北区中之島1丁目3番20号（大阪市役所）","receptionNote":"開庁時間 平日9:00〜17:30。事業別の所管部署は組織・問合せ一覧で確認すること。","sourceUrl":"https://www.city.osaka.lg.jp/port/","confirmedAt":"2026-08-13","notes":"2020/10に大阪市港湾局と大阪府港湾局を統合。詳細な窓口は組織・問合せ一覧を参照（要照会）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('7638e34c-964d-46d1-8610-1452079f040e', '277bd27c-310e-48c0-843b-2dc0aa65b1ac', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-port","officeName":"大阪港湾局（組織・問合せ一覧）","contactType":"phone","label":"大阪市役所代表","displayValue":"06-6208-8181","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/port/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('4b158f9c-eb5e-4fe4-826c-966935812d71', '277bd27c-310e-48c0-843b-2dc0aa65b1ac', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-port","officeName":"大阪港湾局（組織・問合せ一覧）","contactType":"phone","label":"大阪市総合コールセンター（8:00〜21:00）","displayValue":"06-4301-7285","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/port/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a6f4b482-946f-4dbc-8dff-8057f5fd8d8d', '277bd27c-310e-48c0-843b-2dc0aa65b1ac', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"osaka-port","officeName":"大阪港湾局（組織・問合せ一覧）","contactType":"web","label":"大阪港湾局（原典）","displayValue":"https://www.city.osaka.lg.jp/port/","extension":null,"sourceUrl":"https://www.city.osaka.lg.jp/port/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('19ffc09e-e1f8-4292-8b7f-233c065fda79', '32aed493-fc07-45f6-8a3e-2401ca8be075', 'office', '{"entityKind":"office","sourceSlug":"keishicho-road-use","organizationName":"警視庁","officeName":"交通規制課 道路第一係・道路第二係","roleSummary":"道路使用許可の概要、工事・作業（道路第一係）および工事・作業以外（道路第二係）に関する問い合わせ","postalCode":"100-8929","addressRaw":"東京都千代田区霞が関2丁目1番1号（警視庁）","receptionNote":"申請窓口は使用場所を管轄する警察署の交通規制係（受付 平日8:30〜16:30）。高速道路上は高速道路交通警察隊へ申請。","sourceUrl":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","confirmedAt":"2026-08-13","notes":"申請書類・様式の詳細は原典を確認。代表番号は問い合わせ先として記載されており、直接の担当係へつながるとは限らない。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('9c756d7a-59be-4cae-830e-68a7542ce3b5', '32aed493-fc07-45f6-8a3e-2401ca8be075', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"keishicho-road-use","officeName":"交通規制課 道路第一係・道路第二係","contactType":"phone","label":"警視庁代表（交通規制課）","displayValue":"03-3581-4321","extension":null,"sourceUrl":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('d5e75534-3d97-4a96-817b-3815d710588e', '32aed493-fc07-45f6-8a3e-2401ca8be075', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"keishicho-road-use","officeName":"交通規制課 道路第一係・道路第二係","contactType":"web","label":"道路使用許可申請手続き（原典）","displayValue":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","extension":null,"sourceUrl":"https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kotsu/road_permission.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a58271fd-1054-4109-8d1a-4a35ccedc7fb', '5f415257-92df-4914-89c1-6b6ac5bf3af8', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kensetsu-river","organizationName":"東京都建設局","officeName":"河川部 指導調整課 占用担当","roleSummary":"河川占用等に関する問い合わせ（原典「指導調整課占用担当」）","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","confirmedAt":"2026-08-13","notes":"河川利用全般の問い合わせは所管の建設事務所管理課または特別区へ（原典に記載・所管区域は別ページ参照）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('2b3d803f-21f7-422d-881a-322869aa1163', '5f415257-92df-4914-89c1-6b6ac5bf3af8', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-river","officeName":"河川部 指導調整課 占用担当","contactType":"phone","label":"問い合わせ（占用担当）","displayValue":"03-5320-5409","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('6136d82e-28c2-4d9e-829a-14bd34d2cb30', '5f415257-92df-4914-89c1-6b6ac5bf3af8', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-river","officeName":"河川部 指導調整課 占用担当","contactType":"web","label":"河川の管理と活用（原典）","displayValue":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/river/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('25beae98-2cf7-4575-8965-b65cdefb36a4', 'c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kensetsu-road","organizationName":"東京都建設局","officeName":"道路管理部 管理課","roleSummary":"都道の占用許可・特殊車両通行許可等に関する問い合わせ窓口（原典「問い合わせ先：管理課」）","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":"原典ページに受付時間の記載なし（要照会）","sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","confirmedAt":"2026-08-13","notes":"2026-08-13 に公式ページを取得して抽出。道路管理部の組織概要・パンフレット問い合わせ先として管理課 03-5320-5273 を確認。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('625bca7d-6c47-4304-8f46-83d13ea7f638', 'c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-road","officeName":"道路管理部 管理課","contactType":"phone","label":"問い合わせ（管理課）","displayValue":"03-5320-5273","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('e090cb03-9d5e-47d6-865a-83d687929883', 'c6dad15a-ece1-4c23-8aa0-ef4d1f8ef01f', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kensetsu-road","officeName":"道路管理部 管理課","contactType":"web","label":"道路の管理（原典）","displayValue":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","extension":null,"sourceUrl":"https://www.kensetsu.metro.tokyo.lg.jp/road/kanri","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('1e6daa69-de65-4de5-8eb6-51169f8a5d9d', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kouwan-madoguchi","organizationName":"東京都港湾局","officeName":"総務部総務課 広報・国際担当（都民の声総合窓口）","roleSummary":"東京都港湾局の事業に関する総合的な問い合わせ窓口","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13","notes":"提言・要望等はメールでも受付（原典「提言・要望等」ページ参照）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a833c86f-96fa-4e22-8094-dbe6e2ed40f6', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"総務部総務課 広報・国際担当（都民の声総合窓口）","contactType":"phone","label":"港湾局都民の声総合窓口","displayValue":"03-5320-5524","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('16855fec-bf57-4324-8c0d-f6774ee7225e', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"総務部総務課 広報・国際担当（都民の声総合窓口）","contactType":"web","label":"窓口一覧（原典）","displayValue":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a5d00d4c-1fb8-420a-8d5e-63054cc95bd5', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'office', '{"entityKind":"office","sourceSlug":"tokyo-kouwan-madoguchi","organizationName":"東京都港湾局","officeName":"東京港建設事務所 高潮対策センター 防災担当","roleSummary":"水門・陸こうの工事・定期運転についての問い合わせ","postalCode":null,"addressRaw":null,"receptionNote":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13","notes":"住所・受付時間は原典の東京港建設事務所ページを確認すること。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('853941fd-8510-4aa2-8ae9-63356e51417f', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"東京港建設事務所 高潮対策センター 防災担当","contactType":"phone","label":"防災担当","displayValue":"03-3521-3013","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('c99bb39a-03ed-4ff0-8f10-65f48a538688', 'dda736cd-0cc1-45bb-816b-0739bef2e6b0', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-kouwan-madoguchi","officeName":"東京港建設事務所 高潮対策センター 防災担当","contactType":"web","label":"窓口一覧（原典）","displayValue":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","extension":null,"sourceUrl":"https://www.kouwan.metro.tokyo.lg.jp/inquiry/madoguchi","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('03a2fb3d-ed3c-4f10-8b62-334bd7d7b0eb', '75e86800-3359-4fae-85eb-bbdb9c08aa95', 'office', '{"entityKind":"office","sourceSlug":"tokyo-zaimu-keiyaku","organizationName":"東京都財務局","officeName":"経理部総務課 契約調整担当","roleSummary":"契約情報・入札契約に関する問い合わせ","postalCode":"163-8001","addressRaw":"東京都新宿区西新宿2-8-1（東京都庁）","receptionNote":null,"sourceUrl":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","confirmedAt":"2026-08-13","notes":"入札手続きの操作等は東京都電子調達システムの案内を確認すること。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('0b0e7730-bba7-4851-8997-141313f7541f', '75e86800-3359-4fae-85eb-bbdb9c08aa95', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-zaimu-keiyaku","officeName":"経理部総務課 契約調整担当","contactType":"phone","label":"問い合わせ（契約調整担当）","displayValue":"03-5388-2607","extension":null,"sourceUrl":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('583012cc-cb3b-454b-85b0-35bb34981a8c', '75e86800-3359-4fae-85eb-bbdb9c08aa95', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"tokyo-zaimu-keiyaku","officeName":"経理部総務課 契約調整担当","contactType":"web","label":"契約情報（原典）","displayValue":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","extension":null,"sourceUrl":"https://www.zaimu.metro.tokyo.lg.jp/keiyaku","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('8f51e099-6e0b-4a9e-8489-41357f17743a', '8ee69100-9ae5-43b6-826a-00d5e098a46d', 'office', '{"entityKind":"office","sourceSlug":"kanagawa-police-road-use","organizationName":"神奈川県警察本部","officeName":"所轄警察署 道路使用窓口","roleSummary":"道路使用許可の申請・問い合わせ窓口（使用場所を管轄する警察署）","postalCode":null,"addressRaw":null,"receptionNote":"申請書・添付書類を各2通作成し、所轄警察署の道路使用窓口へ提出。受付時間・一括申請可否は管轄警察署へ電話で確認。","sourceUrl":"https://www.police.pref.kanagawa.jp/tetsuzuki/kotsukankei/mesf1016.html","confirmedAt":"2026-08-13","notes":"警察署ごとの電話番号は原典に一覧がないため要照会。道路占用許可は各道路管理者の窓口へ。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('dabfcff7-8b6c-4b68-869b-496efb619ace', '8ee69100-9ae5-43b6-826a-00d5e098a46d', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"kanagawa-police-road-use","officeName":"所轄警察署 道路使用窓口","contactType":"web","label":"道路使用許可（原典）","displayValue":"https://www.police.pref.kanagawa.jp/tetsuzuki/kotsukankei/mesf1016.html","extension":null,"sourceUrl":"https://www.police.pref.kanagawa.jp/tetsuzuki/kotsukankei/mesf1016.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('82d1fc44-583a-4a32-8040-bff05257e336', '913fc3b1-0406-4397-8760-c1424c0d9cee', 'office', '{"entityKind":"office","sourceSlug":"yokohama-kasen-senyo","organizationName":"横浜市（道路局河川部/下水道河川局）","officeName":"下水道河川局 河川流域管理課（および各区土木事務所）","roleSummary":"横浜市管理河川・一般下水道（水路）の占用許可申請先（河川種別で分岐）","postalCode":null,"addressRaw":null,"receptionNote":"申請前に各区土木事務所または河川流域管理課へ相談。受付時間は各窓口を確認。","sourceUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/kasen-gesuido/kasen/youchi/20200715131717128.html","confirmedAt":"2026-08-13","notes":"権限委譲された一級河川は河川流域管理課、二級河川等は区土木事務所（原典の申請先一覧を参照）。国・県管理河川は各管理者へ。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('7ca58eaa-42f6-4028-8a28-6e69fff0d01e', '913fc3b1-0406-4397-8760-c1424c0d9cee', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-kasen-senyo","officeName":"下水道河川局 河川流域管理課（および各区土木事務所）","contactType":"phone","label":"横浜市コールセンター","displayValue":"045-664-2525","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/kasen-gesuido/kasen/youchi/20200715131717128.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('f9c0023d-a693-41c4-8b55-103535d21d0d', '913fc3b1-0406-4397-8760-c1424c0d9cee', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-kasen-senyo","officeName":"下水道河川局 河川流域管理課（および各区土木事務所）","contactType":"web","label":"河川・一般下水道（水路）等の占用許可（原典）","displayValue":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/kasen-gesuido/kasen/youchi/20200715131717128.html","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/kasen-gesuido/kasen/youchi/20200715131717128.html","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('f1cea76c-d4af-4f22-8f8e-45fac77311a4', '87ec249b-62a0-4c23-8043-e2e484fb2d9b', 'office', '{"entityKind":"office","sourceSlug":"yokohama-kowan","organizationName":"横浜市港湾局","officeName":"港湾局（組織案内）","roleSummary":"横浜港の港湾管理・事業に関する問い合わせ（組織案内ページ参照）","postalCode":null,"addressRaw":null,"receptionNote":"事業別の所管部署・窓口は組織案内を確認すること。","sourceUrl":"https://www.city.yokohama.lg.jp/city-info/yokohamashi/org/kowan/","confirmedAt":"2026-08-13","notes":"担当部署の直通番号は原典に記載なし（要照会）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('73bd16ae-9fe9-45a0-8bd8-9ea10e5bc46e', '87ec249b-62a0-4c23-8043-e2e484fb2d9b', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-kowan","officeName":"港湾局（組織案内）","contactType":"phone","label":"横浜市コールセンター","displayValue":"045-664-2525","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/city-info/yokohamashi/org/kowan/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('f69d7520-7256-44fd-8b49-fb4ebc90d349', '87ec249b-62a0-4c23-8043-e2e484fb2d9b', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-kowan","officeName":"港湾局（組織案内）","contactType":"web","label":"港湾局 組織案内（原典）","displayValue":"https://www.city.yokohama.lg.jp/city-info/yokohamashi/org/kowan/","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/city-info/yokohamashi/org/kowan/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('86c01340-5834-4f11-8035-524892cbd836', '64b72adc-beb7-4ff8-83ae-73a966383a80', 'office', '{"entityKind":"office","sourceSlug":"yokohama-nyusatsu","organizationName":"横浜市（財政局契約第一課ほか）","officeName":"横浜市（入札・契約情報）","roleSummary":"横浜市の入札・契約情報の掲載主体。手続きの詳細は案内ページを参照","postalCode":null,"addressRaw":null,"receptionNote":"入札参加・電子入札等の問い合わせ先は案内ページを確認すること。","sourceUrl":"https://www.city.yokohama.lg.jp/business/nyusatsu/","confirmedAt":"2026-08-13","notes":"担当部署の直通番号は原典に記載なし（要照会）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('d353eaa4-658b-48f6-88dd-5c5c2d064453', '64b72adc-beb7-4ff8-83ae-73a966383a80', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-nyusatsu","officeName":"横浜市（入札・契約情報）","contactType":"phone","label":"横浜市コールセンター","displayValue":"045-664-2525","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/business/nyusatsu/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('e6c69f71-905d-48a9-862c-9ab5ffa66c25', '64b72adc-beb7-4ff8-83ae-73a966383a80', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-nyusatsu","officeName":"横浜市（入札・契約情報）","contactType":"web","label":"入札・契約情報（原典）","displayValue":"https://www.city.yokohama.lg.jp/business/nyusatsu/","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/business/nyusatsu/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('5c275fff-023f-48e1-8922-77a66aa842ff', 'c19d9c16-53e3-427a-8d80-9f99d203d58f', 'office', '{"entityKind":"office","sourceSlug":"yokohama-road-senyo","organizationName":"横浜市道路局","officeName":"横浜市（道路占用の手続き）","roleSummary":"横浜市管理道路の占用許可・手続きの案内主体。手続き詳細は案内ページを参照","postalCode":null,"addressRaw":null,"receptionNote":"占用許可基準・手続き・占用料は案内ページを確認。申請窓口の詳細はページ内リンクを参照。","sourceUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/doro/kanri_senyo/senyo/","confirmedAt":"2026-08-13","notes":"担当部署の直通番号は原典に記載なし（要照会）。"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('a03dafec-5f47-468a-887b-1c1df2abc2e2', 'c19d9c16-53e3-427a-8d80-9f99d203d58f', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-road-senyo","officeName":"横浜市（道路占用の手続き）","contactType":"phone","label":"横浜市コールセンター","displayValue":"045-664-2525","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/doro/kanri_senyo/senyo/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
INSERT INTO staging.import_records (id, source_id, entity_kind, raw_payload, quality_flags, review_state)
VALUES ('1f068ed1-0991-486e-826e-89901cd6b38f', 'c19d9c16-53e3-427a-8d80-9f99d203d58f', 'contact_point', '{"entityKind":"contact_point","sourceSlug":"yokohama-road-senyo","officeName":"横浜市（道路占用の手続き）","contactType":"web","label":"道路の占用（原典）","displayValue":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/doro/kanri_senyo/senyo/","extension":null,"sourceUrl":"https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/doro/kanri_senyo/senyo/","confirmedAt":"2026-08-13"}'::jsonb, '["contact_pending_review"]'::jsonb, 'pending')
ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, entity_kind = EXCLUDED.entity_kind, raw_payload = EXCLUDED.raw_payload, quality_flags = EXCLUDED.quality_flags, review_state = EXCLUDED.review_state;
COMMIT;
